# fly.toml app configuration file generated for adcopy on 2025-08-29T02:52:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adcopy'
primary_region = 'phx'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'

[[mounts]]
  source = 'mongo_data'
  destination = '/data/db'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[services]]
  protocol = ''
  internal_port = 27017

  [[services.ports]]
    port = 27017

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
